#############################################################################
# Makefile for building: JQHttpServer
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  JQHttpServer.pro
# Template: subdirs
# Command: D:\Qt\Qt5.14.2\5.14.2\msvc2017\bin\qmake.exe -o Makefile JQHttpServer.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\Qt\Qt5.14.2\5.14.2\msvc2017\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Qt\Qt5.14.2\5.14.2\msvc2017\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Qt\Qt5.14.2\5.14.2\msvc2017\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-tester \
		sub-demos


sub-tester-qmake_all:  FORCE
	@if not exist tester\ mkdir tester\ & if not exist tester\ exit 1
	cd tester\ && $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\tester\tester.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tester\ && $(MAKE) -f Makefile qmake_all
sub-tester: $(MAKEFILE) FORCE
	@if not exist tester\ mkdir tester\ & if not exist tester\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tester\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\tester\tester.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-tester-make_first: FORCE
	@if not exist tester\ mkdir tester\ & if not exist tester\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tester\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\tester\tester.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-tester-all: FORCE
	@if not exist tester\ mkdir tester\ & if not exist tester\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tester\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\tester\tester.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-tester-clean: FORCE
	@if not exist tester\ mkdir tester\ & if not exist tester\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tester\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\tester\tester.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-tester-distclean: FORCE
	@if not exist tester\ mkdir tester\ & if not exist tester\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tester\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\tester\tester.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-tester-install_subtargets: FORCE
	@if not exist tester\ mkdir tester\ & if not exist tester\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tester\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\tester\tester.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-tester-uninstall_subtargets: FORCE
	@if not exist tester\ mkdir tester\ & if not exist tester\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tester\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\tester\tester.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-demos-qmake_all:  FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\demos\demos.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd demos\ && $(MAKE) -f Makefile qmake_all
sub-demos: $(MAKEFILE) FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd demos\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\demos\demos.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-demos-make_first: FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd demos\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\demos\demos.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-demos-all: FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd demos\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\demos\demos.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-demos-clean: FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd demos\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\demos\demos.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-demos-distclean: FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd demos\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\demos\demos.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-demos-install_subtargets: FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd demos\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\demos\demos.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-demos-uninstall_subtargets: FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd demos\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\demos\demos.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: JQHttpServer.pro ..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\win32-msvc\qmake.conf ..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\spec_pre.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\common\angle.conf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\common\windows-desktop.conf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\win32\windows_vulkan_sdk.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\common\windows-vulkan.conf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\common\msvc-desktop.conf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\qconfig.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3danimation.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3danimation_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickanimation.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3drender.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_axbase.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_axserver.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_core.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_dbus.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_edid_support_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_egl_support_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_gamepad.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_help.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_location.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_location_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_network.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_positioningquick.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_positioningquick_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmlmodels.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quickshapes_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quicktemplates2.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_remoteobjects.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_repparser.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_repparser_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_scxml.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_texttospeech.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_texttospeech_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_theme_support_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_websockets.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_webview.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_winextras.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_winextras_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\qt_functions.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\qt_config.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\win32-msvc\qmake.conf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\spec_post.prf \
		.qmake.stash \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\exclusive_builds.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\common\msvc-version.conf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\toolchain.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\default_pre.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\win32\default_pre.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\resolve_config.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\default_post.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\qml_debug.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\precompile_header.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\warn_on.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\qmake_use.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\file_copies.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\win32\windows.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\testcase_targets.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\exceptions.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\yacc.prf \
		..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\lex.prf \
		JQHttpServer.pro
	$(QMAKE) -o Makefile JQHttpServer.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\spec_pre.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\common\angle.conf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\common\windows-desktop.conf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\win32\windows_vulkan_sdk.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\common\windows-vulkan.conf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\common\msvc-desktop.conf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\qconfig.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3danimation.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3danimation_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dcore.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dextras.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dinput.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquick.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickanimation.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickscene2d.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3drender.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_accessibility_support_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_axbase.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_core.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_dbus.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_designer.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_designer_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_edid_support_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_egl_support_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_gamepad.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_gamepad_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_gui.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_help.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_location.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_location_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_network.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_positioningquick.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_positioningquick_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qml.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmlmodels.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmlmodels_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmlworkerscript.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quick.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quickshapes_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quicktemplates2.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_remoteobjects.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_remoteobjects_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_repparser.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_repparser_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_scxml.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_serialbus.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_sql.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_svg.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_texttospeech.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_texttospeech_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_theme_support_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_vulkan_support_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_webchannel.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_webview.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_webview_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_winextras.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_xml.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\qt_functions.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\qt_config.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\win32-msvc\qmake.conf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\spec_post.prf:
.qmake.stash:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\exclusive_builds.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\common\msvc-version.conf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\toolchain.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\default_pre.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\win32\default_pre.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\resolve_config.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\exclusive_builds_post.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\default_post.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\qml_debug.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\precompile_header.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\warn_on.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\qmake_use.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\file_copies.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\win32\windows.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\testcase_targets.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\exceptions.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\yacc.prf:
..\..\..\Qt\Qt5.14.2\5.14.2\msvc2017\mkspecs\features\lex.prf:
JQHttpServer.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile JQHttpServer.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-tester-qmake_all sub-demos-qmake_all FORCE

make_first: sub-tester-make_first sub-demos-make_first  FORCE
all: sub-tester-all sub-demos-all  FORCE
clean: sub-tester-clean sub-demos-clean  FORCE
distclean: sub-tester-distclean sub-demos-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-tester-install_subtargets sub-demos-install_subtargets FORCE
uninstall_subtargets: sub-tester-uninstall_subtargets sub-demos-uninstall_subtargets FORCE

sub-tester-debug:
	@if not exist tester\ mkdir tester\ & if not exist tester\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tester\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\tester\tester.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-demos-debug:
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd demos\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\demos\demos.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-tester-debug sub-demos-debug

sub-tester-release:
	@if not exist tester\ mkdir tester\ & if not exist tester\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tester\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\tester\tester.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-demos-release:
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd demos\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\demos\demos.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-tester-release sub-demos-release

sub-tester-check:
	@if not exist tester\ mkdir tester\ & if not exist tester\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tester\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\tester\tester.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-demos-check:
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd demos\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\demos\demos.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-tester-check sub-demos-check

sub-tester-benchmark:
	@if not exist tester\ mkdir tester\ & if not exist tester\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tester\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\tester\tester.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-demos-benchmark:
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd demos\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\SourceCode\HDS\JQHttpServer\demos\demos.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-tester-benchmark sub-demos-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

